### ISSUE TITLE
Issue during Migration of EPPLUS version

### ISSUE THREAD

**Issue by Sayfouche** [ylatuya/EPPlus#1]
Hello,

I have migrated an existing EPPLUS dll (version 3.0.0.1) to the 4.1.0.
My issue is that some property are not found:
1- InvertIfNegative (ExcelChartseries class)
2- EnableMajorGridLine (ExcelChartAxis class)

why these properties are delete ?
and how can i resolve this problem ?

Saif

**Comment by ylatuya** [comment]
Hi,
This is a personal clone of the original EPPlus repository, please contact with the maintainers instead.
